### ISSUE TITLE
Remove the 'build' folder.

### ISSUE THREAD

**Issue by iAlexT** [AllanGame/minecraft-KillStreak-plugin#2]
Remove the <a href="https://github.com/AllanGame/minecraft-KillStreak-plugin/tree/main/plugin/build">build</a> folder by adding it to the <a href="https://github.com/AllanGame/minecraft-KillStreak-plugin/blob/main/.gitignore">.gitignore</a> file.

**Comment by AllanGame** [comment]
[Done](https://github.com/AllanGame/minecraft-KillStreak-plugin/commit/4ac875460dcbcb546ca9a7f216681e40e26fb605)
