### ISSUE TITLE
Don't break the Liskov Substitution Principle

### ISSUE THREAD

**Issue by iAlexT** [AllanGame/minecraft-KillStreak-plugin#3]
Use <a href="https://docs.oracle.com/javase/8/docs/api/java/util/Map.html">Map</a> instead of <a href="https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html">HashMap</a> in <a href="https://github.com/AllanGame/minecraft-KillStreak-plugin/blob/main/plugin/src/main/java/me/allangame/killstreak/streakmanager/StreakList.java">StreakList</a> to respect the Liskov Substitution Principle.

**Comment by AllanGame** [comment]
[Done](https://github.com/AllanGame/minecraft-KillStreak-plugin/commit/d1b5e882a1dd1dc3cd3f528ccaf0d93d1399b4c9)
