### ISSUE TITLE
Consider avoiding nested if statements

### ISSUE THREAD

**Issue by iAlexT** [AllanGame/minecraft-KillStreak-plugin#4]
In the class <a href="https://github.com/AllanGame/minecraft-KillStreak-plugin/blob/main/plugin/src/main/java/me/allangame/killstreak/listeners/PlayerDeath.java">PlayerDeath</a>, you have lots of nested if statements. In this case, it quite decreases the code readability. You can avoid them inverting the coinditions, like this:
```java
// Nesting
if (coindition) {
  if (anotherCondition) {
    // Do something
  }
}
// Without nesting
if (!condition) {
  return;
}
if (!anotherCondition) {
  return;
}
// Now, do something
```

**Comment by AllanGame** [comment]
[Done](https://github.com/AllanGame/minecraft-KillStreak-plugin/commit/60e4665b2000fa5891a62dc55b2b9337ba729b65)
